import * as am4core from '@amcharts/amcharts4/core';

let large_tree_data = [{
    name: "Health & It",
    text: "Health & It",
    value: 45,
    "g_id": 1,
    "d_id": 1,
    "u_id": 2,
    "t_id": 1,
    sizeFont : 14,
    color: "#64D3BB",
    fixed: true,
    x: am4core.percent(23.25),
    y: am4core.percent(13),
    children: [{
        name: "Present Development",
        text: "Present\nDevelopment",
        value: 27.5,
        "d_id": 1,
        "g_id": 1,
        "u_id": 2,
        "t_id": 1,
        sizeFont : 11,
        fixed: true,
        x: am4core.percent(12),
        y: am4core.percent(35),
        children: [{
            name: "Availability",
            text: "Availability",
            value: 17.5,
            "u_id": 2,
            "d_id": 1,
            "g_id": 1,
            "t_id": 1,
            sizeFont : 9,
            fixed: true,
            x: am4core.percent(6),
            y: am4core.percent(55),
            children: [{
                name: "AI Workforce/Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 5,
                "g_id": 1,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(2),
                y: am4core.percent(70),
            }, {
                name: "Healthcare Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 1,
                "g_id": 1,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(3.5),
                y: am4core.percent(74),
            }, {
                name: "Healthcare workforce and Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 4,
                "g_id": 1,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(6),
                y: am4core.percent(76),
            }, {
                name: "IT Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 2,
                "g_id": 1,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(8.5),
                y: am4core.percent(74),
            }, {
                name: "IT Workforce & Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 3,
                "g_id": 1,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(10),
                y: am4core.percent(70),
            }]
        }, {
            name: "Readiness",
            text: "Readiness",
            value: 17.5,
            "u_id": 1,
            "d_id": 1,
            "g_id": 1,
            "t_id": 1,
            sizeFont : 9,
            fixed: true,
            x: am4core.percent(18),
            y: am4core.percent(55),
            children: [{
                name: "AI Workforce/Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 5,
                "g_id": 1,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(14),
                y: am4core.percent(70),
            }, {
                name: "Healthcare Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 1,
                "g_id": 1,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(15.5),
                y: am4core.percent(74),
            }, {
                name: "Healthcare workforce and Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 4,
                "g_id": 1,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(18),
                y: am4core.percent(76),
            }, {
                name: "IT Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 2,
                "g_id": 1,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(20.5),
                y: am4core.percent(74),
            }, {
                name: "IT Workforce & Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 3,
                "g_id": 1,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(22),
                y: am4core.percent(70),
            }]
        }]
    }, {
        name: "Prospective Development",
        text: "Prospective\nDevelopment",
        value: 27.5,
        "d_id": 2,
        "g_id": 1,
        "u_id": 3,
        "t_id": 1,
        sizeFont : 11,
        fixed: true,
        x: am4core.percent(34.5),
        y: am4core.percent(35),
        children: [{
            name: "Capacity Building",
            text: "Capacity\nBuilding",
            value: 17.5,
            "u_id": 4,
            "d_id": 2,
            "g_id": 1,
            "t_id": 1,
            sizeFont : 9,
            fixed: true,
            x: am4core.percent(29),
            y: am4core.percent(55),
            children: [{
                name: "AI Workforce/Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 5,
                "g_id": 1,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(25),
                y: am4core.percent(70),
            }, {
                name: "Healthcare Governance",
                text: "",
                children:[{}],
                value: 1,
                fixed: true,
                "t_id": 1,
                "g_id": 1,
                "d_id": 2,
                "u_id": 4,
                x: am4core.percent(26.5),
                y: am4core.percent(74),
            }, {
                name: "Healthcare workforce and Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 4,
                "g_id": 1,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(29),
                y: am4core.percent(76),
            }, {
                name: "IT Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 2,
                sizeFont : 0,
                "g_id": 1,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(31.5),
                y: am4core.percent(74),
            }, {
                name: "IT Workforce & Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 3,
                sizeFont : 0,
                "g_id": 1,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(33),
                y: am4core.percent(70),
            }]
        }, {
            name: "Development Strategy",
            text: "Development\nStrategy",
            value: 17.5,
            "u_id": 3,
            "d_id": 2,
            "g_id": 1,
            "t_id": 1,
            sizeFont : 9,
            fixed: true,
            x: am4core.percent(40),
            y: am4core.percent(55),
            children: [{
                name: "AI Workforce/Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 5,
                sizeFont : 0,
                "g_id": 1,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(36),
                y: am4core.percent(70),
            }, {
                name: "Healthcare Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 1,
                sizeFont : 0,
                "g_id": 1,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(37.5),
                y: am4core.percent(74),
            }, {
                name: "Healthcare workforce and Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 4,
                sizeFont : 0,
                "g_id": 1,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(40),
                y: am4core.percent(76),
            }, {
                name: "IT Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 2,
                sizeFont : 0,
                "g_id": 1,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(42.5),
                y: am4core.percent(74),
            }, {
                name: "IT Workforce & Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 3,
                sizeFont : 0,
                "g_id": 1,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(44),
                y: am4core.percent(70),
            }]
        }]
    }]
}, {
    name: "Digital Health",
    text: "Digital Health",
    value: 45,
    color: "#5470C6",
    fixed: true,
    "g_id": 2,
    "d_id": 1,
    "u_id": 2,
    "t_id": 6,
    sizeFont : 14,
    x: am4core.percent(72.25),
    y: am4core.percent(13),
    children: [{
        name: "Present Development",
        text: "Present\nDevelopment",
        value: 27.5,
        "d_id": 1,
        "g_id": 2,
        "u_id": 2,
        "t_id": 6,
        sizeFont : 11,
        fixed: true,
        x: am4core.percent(58.5),
        y: am4core.percent(35),
        children: [{
            name: "Availability",
            text: "Availability",
            value: 17.5,
            "u_id": 2,
            "d_id": 1,
            "g_id": 2,
            "t_id": 6,
            sizeFont : 9,
            fixed: true,
            x: am4core.percent(51.5),
            y: am4core.percent(55),
            children: [
                {
                name: "DH Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 7,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(46.5),
                y: am4core.percent(66),
            }, {
                name: "Digital Health (DH) Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 6,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(47.5),
                y: am4core.percent(70),
            }, {
                name: "Funding and resources",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 9,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(49),
                y: am4core.percent(74),
            }, {
                name: "Legal rules",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 10,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(51.5),
                y: am4core.percent(76),
            }, {
                name: "Literacy (patient+ workforce)",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 12,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(54),
                y: am4core.percent(74),
            }, {
                name: "Research Program and funding",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 11,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(55.5),
                y: am4core.percent(70),
            }, {
                name: "Workforce (Technical and Health care)",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 8,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 2,
                fixed: true,
                x: am4core.percent(56.5),
                y: am4core.percent(66),
            }]
        }, {
            name: "Readiness",
            text: "Readiness",
            value: 17.5,
            "u_id": 1,
            "d_id": 1,
            "g_id": 2,
            "t_id": 6,
            sizeFont : 9,
            fixed: true,
            x: am4core.percent(65.5),
            y: am4core.percent(55),
            children: [{
                name: "DH Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 7,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(60.5),
                y: am4core.percent(66),
            }, {
                name: "Digital Health (DH) Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 6,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(61.5),
                y: am4core.percent(70),
            }, {
                name: "Funding and resources",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 9,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(63),
                y: am4core.percent(74),
            }, {
                name: "Legal rules",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 10,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(65.5),
                y: am4core.percent(76),
            }, {
                name: "Literacy (patient+ workforce)",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 12,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(68),
                y: am4core.percent(74),
            }, {
                name: "Research Program and funding",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 11,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(69.5),
                y: am4core.percent(70),
            }, {
                name: "Workforce (Technical and Health care)",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 8,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 1,
                "u_id": 1,
                fixed: true,
                x: am4core.percent(70.5),
                y: am4core.percent(66),
            }]
        }]
    }, {
        name: "Prospective Development",
        text: "Prospective\nDevelopment",
        value: 27.5,
        "d_id": 2,
        "g_id": 2,
        "u_id": 4,
        "t_id": 6,
        sizeFont : 11,
        fixed: true,
        x: am4core.percent(86),
        y: am4core.percent(35),
        children: [{
            name: "Capacity Building",
            text: "Capacity\nBuilding",
            value: 17.5,
            "u_id": 4,
            "d_id": 2,
            "g_id": 2,
            "t_id": 6,
            sizeFont : 9,
            fixed: true,
            x: am4core.percent(79),
            y: am4core.percent(55),
            children: [{
                name: "DH Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 7,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(74),
                y: am4core.percent(66),
            }, {
                name: "Digital Health (DH) Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 6,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(75),
                y: am4core.percent(70),
            }, {
                name: "Funding and resources",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 9,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(76.5),
                y: am4core.percent(74),
            }, {
                name: "Legal rules",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 10,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(79),
                y: am4core.percent(76),
            }, {
                name: "Literacy (patient+ workforce)",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 12,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(81.5),
                y: am4core.percent(74),
            }, {
                name: "Research Program and funding",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 11,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(83),
                y: am4core.percent(70),
            }, {
                name: "Workforce (Technical and Health care)",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 8,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 4,
                fixed: true,
                x: am4core.percent(84),
                y: am4core.percent(66),
            }]
        }, {
            name: "Development Strategy",
            text: "Development\nStrategy",
            value: 17.5,
            "u_id": 3,
            "d_id": 2,
            "g_id": 2,
            "t_id": 6,
            sizeFont : 9,
            fixed: true,
            x: am4core.percent(93),
            y: am4core.percent(55),
            children: [{
                name: "DH Infrastructure",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 7,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(88),
                y: am4core.percent(66),
            }, {
                name: "Digital Health (DH) Governance",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 6,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(89),
                y: am4core.percent(70),
            }, {
                name: "Funding and resources",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 9,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(90.5),
                y: am4core.percent(74),
            }, {
                name: "Legal rules",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 10,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(93),
                y: am4core.percent(76),
            }, {
                name: "Literacy (patient+ workforce)",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 12,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(95.5),
                y: am4core.percent(74),
            }, {
                name: "Research Program and funding",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 11,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(97),
                y: am4core.percent(70),
            }, {
                name: "Workforce (Technical and Health care)",
                text: "",
                children:[{}],
                value: 1,
                "t_id": 8,
                sizeFont : 0,
                "g_id": 2,
                "d_id": 2,
                "u_id": 3,
                fixed: true,
                x: am4core.percent(98),
                y: am4core.percent(66),
            }]
        }]
    }]
}
];

export default large_tree_data;